import{useEffect,useState}from'react';
import{Settings,Cloud,CheckCircle2,Bell,Link2,ShieldCheck}from'lucide-react';
import{loadAccountSettings,saveAccountSettings,supabaseConfigured}from'./dataStore';

type AccountSettings={agencyName:string;financeEmail:string;pix:string;email:boolean;clientAlerts:boolean};
const defaults:AccountSettings={agencyName:'Design Value',financeEmail:'financeiro@designvalue.com.br',pix:'financeiro@designvalue.com.br',email:true,clientAlerts:true};
const Button=({children,onClick}:{children:any,onClick?:()=>void})=><button className="button primary" onClick={onClick}>{children}</button>;

export default function SettingsPage({notify}:{notify:(message:string)=>void}){
 const[settings,setSettings]=useState<AccountSettings>(()=>{try{return{...defaults,...JSON.parse(localStorage.getItem('dv-settings')||'{}')}}catch{return defaults}}),[drive,setDrive]=useState(()=>localStorage.getItem('dv-drive-connected')==='true'),[saved,setSaved]=useState(true);
 useEffect(()=>localStorage.setItem('dv-drive-connected',String(drive)),[drive]);
 useEffect(()=>{if(!supabaseConfigured)return;loadAccountSettings<AccountSettings>().then(remote=>{if(remote){setSettings({...defaults,...remote});localStorage.setItem('dv-settings',JSON.stringify(remote))}}).catch(console.warn)},[]);
 const update=<K extends keyof AccountSettings>(key:K,value:AccountSettings[K])=>{setSettings({...settings,[key]:value});setSaved(false)};
 const save=async()=>{localStorage.setItem('dv-settings',JSON.stringify(settings));try{if(supabaseConfigured)await saveAccountSettings(settings);setSaved(true);notify(supabaseConfigured?'Dados salvos e sincronizados no Supabase.':'Dados salvos neste navegador.')}catch(error){console.warn(error);notify('Dados salvos localmente; a sincronização está indisponível.')}};
 return <div><div className="page-title"><div><span className="eyebrow">PREFERÊNCIAS DA CONTA</span><h1>Configurações</h1><p>Integrações, notificações e dados da agência.</p></div><Button onClick={save}><CheckCircle2/>{saved?'Dados salvos':'Salvar alterações'}</Button></div><div className="settings-grid"><div><section className="surface settings-section"><div className="settings-title"><Settings/><span><h2>Dados da agência</h2><p>Informações usadas nos portais e documentos.</p></span></div><label>Nome da agência<input value={settings.agencyName} onChange={e=>update('agencyName',e.target.value)}/></label><label>E-mail financeiro<input type="email" value={settings.financeEmail} onChange={e=>update('financeEmail',e.target.value)}/></label><label>Chave Pix<input value={settings.pix} onChange={e=>update('pix',e.target.value)}/></label></section><section className="surface settings-section"><div className="settings-title"><Bell/><span><h2>Notificações</h2><p>Escolha quais eventos precisam da sua atenção.</p></span></div><Toggle label="Avisos por e-mail" note="Receber resumos e alertas de prazo" value={settings.email} set={v=>update('email',v)}/><Toggle label="Atividade do cliente" note="Aberturas, comentários e materiais enviados" value={settings.clientAlerts} set={v=>update('clientAlerts',v)}/></section></div><aside><section className="surface integration-card"><Cloud/><span>GOOGLE DRIVE</span><h2>{drive?'Conectado':'Não conectado'}</h2><p>{drive?'Conta conectada para entregas e monitoramento de pastas.':'Conecte o Drive para publicar entregas e detectar novos arquivos.'}</p><em className={drive?'connected':''}>{drive?'CONECTADO':'DESCONECTADO'}</em><Button onClick={()=>{setDrive(!drive);notify(drive?'Google Drive desconectado.':'Google Drive conectado em modo de demonstração.')}}>{drive?'Desconectar':'Conectar Google Drive'}</Button></section><section className="surface security-card"><ShieldCheck/><h3>Persistência dos dados</h3><p>{supabaseConfigured?'Supabase configurado. Projetos, clientes e dados da agência são sincronizados entre dispositivos.':'Dados salvos neste navegador. Configure o Supabase para sincronizar entre dispositivos.'}</p><button><Link2/>{supabaseConfigured?'Supabase conectado':'Configurar integração'}</button></section></aside></div></div>
}

function Toggle({label,note,value,set}:{label:string;note:string;value:boolean;set:(value:boolean)=>void}){return <div className="settings-toggle"><span><b>{label}</b><small>{note}</small></span><button className={value?'on':''} onClick={()=>set(!value)} aria-pressed={value}><i/></button></div>}
